---
- name: SVN checkout public和platform代码
  hosts: game_servers
  become: true
  gather_facts: true
  vars_files:
    - vars/game-deploy-vars.yml
  vars:
    # 日志配置
    log_file: "logs/game-public_platform.log"
    playbook_name: "game-public_platform"

    # SVN URLs
    svn_public_url: "{{ svn_root_url }}/{{ project_base_dir }}/{{ public_file_path }}"
    svn_platform_url: "{{ svn_root_url }}/{{ project_base_dir }}/{{ platform_path }}"
    # 本地路径
    local_public_dir: "{{ project_root_dir }}/{{ project_base_dir }}/{{ public_file_path }}"
    local_platform_dir: "{{ project_root_dir }}/{{ project_base_dir }}/{{ platform_path }}"
  tasks:
    - name: 创建日志目录
      ansible.builtin.file:
        path: "logs"
        state: directory
        mode: "0755"
      delegate_to: localhost

    - name: 记录代码检出开始日志
      ansible.builtin.lineinfile:
        path: "{{ log_file }}"
        line: >
          [{{ ansible_date_time.iso8601 }}] [{{ playbook_name }}] [NOTICE] SVN代码检出开始 -
          主机={{ inventory_hostname }}, SVN版本={{ svn_revision | default('最新版本') }}
        create: true
        mode: "0644"
      delegate_to: localhost

    - name: 显示checkout开始信息
      ansible.builtin.debug:
        msg: |
          开始SVN checkout操作
          Public URL: {{ svn_public_url }}
          Platform URL: {{ svn_platform_url }}
          {% if svn_revision is defined %}
          指定版本: {{ svn_revision }}
          {% else %}
          版本: 最新版本
          {% endif %}

    - name: 验证svn_revision参数（如果提供）
      ansible.builtin.assert:
        that:
          - svn_revision | regex_search('^[0-9]+$')
        fail_msg: "svn_revision必须是数字版本号"
      when: svn_revision is defined and svn_revision != ""

    - name: 检查并创建项目根目录
      ansible.builtin.file:
        path: "{{ project_root_dir }}/{{ project_base_dir }}"
        state: directory
        mode: '0755'

    - name: SVN checkout public代码（指定版本）
      ansible.builtin.subversion:
        repo: "{{ svn_public_url }}"
        dest: "{{ local_public_dir }}"
        revision: "{{ svn_revision }}"
        force: true
        checkout: true
      register: public_checkout_result
      when: svn_revision is defined and svn_revision != ""

    - name: SVN checkout public代码（最新版本）
      ansible.builtin.subversion:
        repo: "{{ svn_public_url }}"
        dest: "{{ local_public_dir }}"
        force: true
        checkout: true
      register: public_checkout_latest_result
      when: svn_revision is not defined or svn_revision == ""

    - name: SVN checkout platform代码（指定版本）
      ansible.builtin.subversion:
        repo: "{{ svn_platform_url }}"
        dest: "{{ local_platform_dir }}"
        revision: "{{ svn_revision }}"
        force: true
        checkout: true
      register: platform_checkout_result
      when: svn_revision is defined and svn_revision != ""

    - name: SVN checkout platform代码（最新版本）
      ansible.builtin.subversion:
        repo: "{{ svn_platform_url }}"
        dest: "{{ local_platform_dir }}"
        force: true
        checkout: true
      register: platform_checkout_latest_result
      when: svn_revision is not defined or svn_revision == ""

    - name: 验证public目录checkout成功
      ansible.builtin.stat:
        path: "{{ local_public_dir }}"
      register: public_final_check
      failed_when: not public_final_check.stat.exists

    - name: 验证platform目录checkout成功
      ansible.builtin.stat:
        path: "{{ local_platform_dir }}"
      register: platform_final_check
      failed_when: not platform_final_check.stat.exists

    - name: 设置目录权限
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
        recurse: true
      loop:
        - "{{ local_public_dir }}"
        - "{{ local_platform_dir }}"

    - name: 记录代码检出成功日志
      ansible.builtin.lineinfile:
        path: "{{ log_file }}"
        line: >
          [{{ ansible_date_time.iso8601 }}] [{{ playbook_name }}] [NOTICE] SVN代码检出完成 -
          主机={{ inventory_hostname }}, Public目录={{ local_public_dir }}, Platform目录={{ local_platform_dir }},
          版本={{ svn_revision | default('最新版本') }}
        mode: "0644"
      delegate_to: localhost

    - name: 显示checkout完成信息
      ansible.builtin.debug:
        msg: |
          ✅ SVN checkout完成！
          Public目录: {{ local_public_dir }}
          Platform目录: {{ local_platform_dir }}
          {% if svn_revision is defined %}
          检出版本: {{ svn_revision }}
          {% else %}
          检出版本: 最新版本
          {% endif %}
