---
# 美国Tongits日志数据库服务器2 - us-stardb-02
server_name: "us-tongits-log-slave"
ansible_host: "52.9.199.61"
description: "美国Tongits日志数据库服务器2"
service_role: "tongits_log_database"
service_type: "tongits_log_database"
service_category: "database"
region: "united_states"
db_type: "tongits_log"
db_role: "slave"
log_level: "info"
monitoring_enabled: true
backup_required: true
backup_schedule: "daily"
read_only: true
replication_enabled: true
master_host: "us-stardb-01"
