---
# Ansible Inventory Configuration
# 定义游戏服务器基础设施的主机和主机组
all:
  # 全局变量
  vars:
    ansible_user: jms_admin
    ansible_ssh_private_key_file: ~/.ssh/jms_admin.key
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  
  # 主机定义 - 按地理位置和功能分组
  hosts:
    # ======================
    # Singapore (SG) 主机
    # ======================
    
    # 基础设施服务器
    pre:
      ansible_host: 172.31.40.106
      description: "预生产环境服务器"
      environment: "staging"
    
    # Web服务器
    sg-front:
      ansible_host: 172.31.40.103
      description: "新加坡前端Web服务器"
      service_role: "frontend"
    sg-back:
      ansible_host: 172.31.40.104
      description: "新加坡后端Web服务器"
      service_role: "backend"
    
    # Tongits数据库服务器
    sg-tongits:
      ansible_host: 172.31.40.100
      description: "新加坡Tongits游戏数据库服务器"
      service_role: "tongits_database"
      db_type: "tongits"
      port: 3306
    
    # Tongits日志数据库服务器
    sg-tongits_log-mas:
      ansible_host: 172.31.40.105
      description: "新加坡Tongits日志数据库主服务器"
      service_role: "tongits_log_database"
      db_type: "tongits_log"
      db_role: "master"
      port: [3306, 3308]
      primary_port: 3308
      secondary_port: 3306
    sg-tongits_log-slv:
      ansible_host: 172.31.40.116
      description: "新加坡Tongits日志数据库从服务器"
      service_role: "tongits_log_database"
      db_type: "tongits_log"
      db_role: "slave"
      port: 3308
    
    # 缓存服务器
    sg-redis:
      ansible_host: 172.31.40.101
      description: "新加坡Redis缓存服务器"
      service_role: "cache"
    
    # 核心服务器
    sg-core-01:
      ansible_host: 172.31.21.117
      description: "新加坡核心服务器1"
      service_role: "core"
    sg-core-02:
      ansible_host: 172.31.38.189
      description: "新加坡核心服务器2"
      service_role: "core"
    
    # 游戏服务器
    sg-game-01:
      ansible_host: 172.31.40.102
      description: "新加坡游戏服务器1"
      service_role: "game"
    sg-game-02:
      ansible_host: 172.31.24.81
      description: "新加坡游戏服务器2"
      service_role: "game"
    sg-game-03:
      ansible_host: 172.31.37.166
      description: "新加坡游戏服务器3"
      service_role: "game"
    
    # 管理服务器
    sg-pdadmin:
      ansible_host: 172.31.20.208
      description: "新加坡管理后台服务器"
      service_role: "admin"
    
    # ======================
    # United States (US) 主机
    # ======================
    
    # Web服务器
    us-front:
      ansible_host: 54.177.98.116
      description: "美国前端Web服务器"
      service_role: "frontend"
    us-back:
      ansible_host: 50.18.221.19
      description: "美国后端Web服务器"
      service_role: "backend"
    
    # Tongits数据库服务器
    us-db-01:
      ansible_host: 54.153.125.96
      description: "美国Tongits数据库服务器1"
      service_role: "tongits_database"
      db_type: "tongits"
      db_role: "master"
      port: 25678
    us-db-02:
      ansible_host: 54.153.90.125
      description: "美国Tongits数据库服务器2"
      service_role: "tongits_database"
      db_type: "tongits"
      db_role: "slave"
      port: 25678
    
    # Tongits日志数据库服务器
    us-stardb-01:
      ansible_host: 52.52.36.197
      description: "美国Tongits日志数据库服务器1"
      service_role: "tongits_log_database"
      db_type: "tongits_log"
      db_role: "master"
      port: 25678
    us-stardb-02:
      ansible_host: 52.9.199.61
      description: "美国Tongits日志数据库服务器2"
      service_role: "tongits_log_database"
      db_type: "tongits_log"
      db_role: "slave"
      port: 25678
    
    # 缓存服务器
    us-redis:
      ansible_host: 13.57.106.117
      description: "美国Redis缓存服务器"
      service_role: "cache"
    
    # 核心服务器
    us-core-01:
      ansible_host: 13.56.36.236
      description: "美国核心服务器1"
      service_role: "core"
    us-core-02:
      ansible_host: 54.151.58.80
      description: "美国核心服务器2"
      service_role: "core"
    
    # 游戏服务器
    us-game-01:
      ansible_host: 54.193.95.19
      description: "美国游戏服务器1"
      service_role: "game"
    us-game-02:
      ansible_host: 52.8.121.171
      description: "美国游戏服务器2"
      service_role: "game"
    
    # 管理服务器
    us-pdadmin:
      ansible_host: 54.215.183.210
      description: "美国管理后台服务器"
      service_role: "admin"

  # 主机组定义
  children:
    # ======================
    # 地理位置分组
    # ======================
    singapore:
      hosts:
        pre:
        sg-front:
        sg-back:
        sg-tongits:
        sg-tongits_log-mas:
        sg-tongits_log-slv:
        sg-redis:
        sg-core-01:
        sg-core-02:
        sg-game-01:
        sg-game-02:
        sg-game-03:
        sg-pdadmin:
      vars:
        region: "singapore"
        timezone: "Asia/Singapore"
        aws_region: "ap-southeast-1"
    
    united_states:
      hosts:
        us-front:
        us-back:
        us-db-01:
        us-db-02:
        us-stardb-01:
        us-stardb-02:
        us-redis:
        us-core-01:
        us-core-02:
        us-game-01:
        us-game-02:
        us-pdadmin:
      vars:
        region: "united_states"
        timezone: "America/Los_Angeles"
        aws_region: "us-west-1"
    
    # ======================
    # 功能分组
    # ======================
    
    # Web服务器组
    web_servers:
      children:
        frontend_servers:
        backend_servers:
      vars:
        service_category: "web"
    
    frontend_servers:
      hosts:
        sg-front:
        us-front:
      vars:
        service_type: "frontend"
        port: 80
        
    backend_servers:
      hosts:
        sg-back:
        us-back:
      vars:
        service_type: "backend"
        port: 80
    
    # 数据库服务器组
    database_servers:
      children:
        sg_tongits_databases:
        us_tongits_databases:
        us_tongits_log_databases:
      vars:
        service_category: "database"
    
    sg_tongits_databases:
      hosts:
        sg-tongits:
        sg-tongits_log-mas:
        sg-tongits_log-slv:
      vars:
        service_type: "tongits_database"
    
    us_tongits_databases:
      hosts:
        us-db-01:
        us-db-02:
      vars:
        service_type: "tongits_database"
    
    us_tongits_log_databases:
      hosts:
        us-stardb-01:
        us-stardb-02:
      vars:
        service_type: "tongits_log_database"
    
    # 缓存服务器组
    cache_servers:
      hosts:
        sg-redis:
        us-redis:
      vars:
        service_type: "cache"
        port: 6380
    
    # 核心服务器组
    core_servers:
      hosts:
        sg-core-01:
        sg-core-02:
        us-core-01:
        us-core-02:
      vars:
        service_type: "core"
    
    # 新加坡游戏服务器组
    sg_game_servers:
      hosts:
        sg-game-01:
        sg-game-02:
        sg-game-03:
      vars:
        service_type: "game"
    # 美国游戏服务器组
    us_game_servers:
      hosts:
        us-game-01:
        us-game-02:
      vars:
        service_type: "game"
    # 演示站
    pre_game_servers:
      hosts:
        pre:
      vars:
        service_type: "game"
        
    # 管理后台服务器组
    admin_servers:
      hosts:
        sg-pdadmin:
        us-pdadmin:
      vars:
        service_type: "admin"
        port: 80
    
    # ======================
    # 数据库角色分组
    # ======================
    
    # 主数据库服务器
    master_databases:
      hosts:
        sg-tongits_log-mas:
        us-db-01:
        us-stardb-01:
      vars:
        db_role: "master"
        read_only: false
    
    # 从数据库服务器
    slave_databases:
      hosts:
        sg-tongits_log-slv:
        us-db-02:
        us-stardb-02:
      vars:
        db_role: "slave"
        read_only: true
    
    # ======================
    # 环境分组
    # ======================
    
    # 生产环境
    production:
      children:
        singapore:
        united_states:
      vars:
        environment: "production"
        log_level: "info"
    
    # 预生产环境
    staging:
      hosts:
        pre:
      vars:
        environment: "staging"
        log_level: "debug"
    
    # ======================
    # 维护分组
    # ======================
    
    # 需要定期备份的服务器
    backup_required:
      children:
        database_servers:
        cache_servers:
      vars:
        backup_schedule: "daily"
    
    # 需要监控的关键服务器
    critical_servers:
      children:
        database_servers:
        web_servers:
        core_servers:
      vars:
        monitoring: "enabled"
        alert_level: "high"
