---
# 游戏服务器部署主任务文件

- name: 设置部署变量
  ansible.builtin.set_fact:
    gameserver_deploy_start_time: "{{ ansible_date_time.iso8601 }}"
  tags: always

- name: 参数验证和日志初始化
  ansible.builtin.include_tasks: validate.yml
  tags: validate

- name: 检查系统依赖
  ansible.builtin.include_tasks: dependencies.yml
  tags: dependencies

- name: 创建必要目录
  ansible.builtin.include_tasks: directories.yml
  tags: directories

- name: 处理SVN操作
  ansible.builtin.include_tasks: svn.yml
  tags: svn

- name: 编译游戏
  ansible.builtin.include_tasks: compile.yml
  tags: compile

- name: 部署游戏服务器
  ansible.builtin.include_tasks: deploy.yml
  tags: deploy

- name: 配置游戏服务器
  ansible.builtin.include_tasks: configure.yml
  tags: configure

- name: 配置和启动Supervisor
  ansible.builtin.include_tasks: supervisor.yml
  tags: supervisor

- name: 记录部署完成和显示结果
  ansible.builtin.include_tasks: summary.yml
  tags: summary
