---
# 部署总结和结果显示

- name: 记录部署完成日志
  ansible.builtin.lineinfile:
    path: "{{ gameserver_deploy_log_file }}"
    line: >
      [{{ ansible_date_time.iso8601 }}] [{{ gameserver_deploy_playbook_name }}] [NOTICE] 游戏服务器部署完成 -
      主机={{ inventory_hostname }}, {{ supervisor_program_name }}, 启动状态={{ gameserver_start_supervisor | default(false) }}
    mode: "0644"
  delegate_to: localhost

- name: 显示部署结果
  ansible.builtin.debug:
    msg: |
      ==================== 部署完成 ====================
      主机: {{ inventory_hostname }} ({{ ansible_host }})
      游戏名称: {{ game_name }}
      游戏ID: {{ game_id }}
      房间号: {{ room_num }}
      游戏房间: {{ game_room }}
      服务名称: {{ supervisor_program_name }}
      部署目录: {{ host_gameserver_dir }}
      编译产物: {{ gameserver_so_file }}
      模板路径: {{ host_gameserver_tmp }}
      {% if gameserver_start_supervisor | default(false) %}
      ==================== 服务状态 ====================
      服务状态: {{ gameserver_final_status.state | default('未知') }}
      日志位置: {{ host_gameserver_dir }}/log/
      访问日志: {{ host_gameserver_dir }}/log/{{ supervisor_program_name }}-access.log
      错误日志: {{ host_gameserver_dir }}/log/{{ supervisor_program_name }}-error.log
      
      手动管理命令:
      启动服务: sudo supervisorctl start {{ supervisor_program_name }}
      停止服务: sudo supervisorctl stop {{ supervisor_program_name }}
      重启服务: sudo supervisorctl restart {{ supervisor_program_name }}
      查看状态: sudo supervisorctl status {{ supervisor_program_name }}
      {% else %}
      ==================== 手动启动 ====================
      Supervisor进程未自动启动，如需启动请手动执行：
      sudo supervisorctl reread && sudo supervisorctl update
      sudo supervisorctl start {{ supervisor_program_name }}
      {% endif %}
      ================================================

- name: 显示快速访问信息
  ansible.builtin.debug:
    msg: |
      快速访问命令:
      查看服务状态: sudo supervisorctl status {{ supervisor_program_name }}
      查看实时日志: tail -f {{ host_gameserver_dir }}/log/{{ supervisor_program_name }}-access.log
      查看错误日志: tail -f {{ host_gameserver_dir }}/log/{{ supervisor_program_name }}-error.log
      进入部署目录: cd {{ host_gameserver_dir }}
