---
# Supervisor配置和启动任务

- name: 创建supervisor配置文件
  ansible.builtin.template:
    src: "{{ host_supervisor_config }}"
    dest: "{{ gameserver_supervisor_dir }}/{{ supervisor_config_file_name }}"
    mode: "0644"

- name: 显示supervisor启动选项
  ansible.builtin.debug:
    msg: |
      Supervisor配置文件已创建: {{ gameserver_supervisor_dir }}/{{ supervisor_program_name }}.conf
      {% if gameserver_start_supervisor | default(false) %}
      即将启动supervisor进程...
      {% else %}
      跳过启动supervisor进程（gameserver_start_supervisor=false）
      {% endif %}

- name: 启动supervisor进程
  ansible.builtin.command: "{{ item }}"
  loop:
    - supervisorctl reread
    - supervisorctl update
  when: gameserver_start_supervisor | default(false) | bool
  changed_when: true

- name: 验证服务启动状态
  community.general.supervisorctl:
    name: "{{ supervisor_program_name }}"
    state: present
  register: gameserver_final_status
  retries: 30
  delay: 1
  until: gameserver_final_status.state == 'RUNNING'
  failed_when: gameserver_final_status.state in ['FATAL', 'EXITED']
  when: gameserver_start_supervisor | default(false) | bool
  changed_when: false
