---
# 游戏服务器部署任务

- name: 检查现有游戏服务器目录
  ansible.builtin.stat:
    path: "{{ gameserver_host_dir }}"
  register: gameserver_existing_server_stat

- name: 检查模板目录存在
  ansible.builtin.stat:
    path: "{{ gameserver_host_tmp }}"
  register: gameserver_template_dir_stat
  failed_when: not gameserver_template_dir_stat.stat.exists

- name: 复制模板文件到服务器目录
  ansible.builtin.shell: |
    shopt -s dotglob && cp -a "{{ gameserver_host_tmp }}"/* "{{ gameserver_host_dir }}"/
  args:
    executable: /bin/bash
  changed_when: true
  tags: gameserver_template

- name: 复制编译产物到服务器目录
  ansible.builtin.copy:
    src: "{{ gameserver_so_file_dir }}/{{ gameserver_so_file }}"
    dest: "{{ gameserver_host_dir }}/{{ gameserver_so_file }}"
    mode: "{{ gameserver_exec_mode }}"
    owner: "{{ gameserver_supervisor_user }}"
    group: "{{ gameserver_supervisor_user }}"
    remote_src: true

- name: 检查room文件是否存在
  ansible.builtin.stat:
    path: "{{ gameserver_host_dir }}/room"
  register: gameserver_room_file_stat

- name: 重命名启动文件
  ansible.builtin.command: mv {{ gameserver_host_dir }}/room {{ gameserver_host_dir }}/{{ gameserver_start_file }}
  when: gameserver_room_file_stat.stat.exists
  changed_when: true

- name: 设置启动文件权限
  ansible.builtin.file:
    path: "{{ gameserver_host_dir }}/{{ gameserver_start_file }}"
    mode: "{{ gameserver_exec_mode }}"
    owner: "{{ gameserver_supervisor_user }}"
    group: "{{ gameserver_supervisor_user }}"
